services:
  - type: web
    name: agriconnect-api
    env: node
    plan: free
    rootDir: backend
    # Install dev dependencies to ensure Nest CLI is available, generate Prisma Client, and build the TS code
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: binary
      - key: PRISMA_CLI_QUERY_ENGINE_TYPE
        value: binary
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_API_KEY
        sync: false
      - key: TWILIO_API_SECRET
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: CV_AI_SERVICE_URL
        value: "https://agriconnect-cv-ai.onrender.com"
      - key: VOICE_AI_SERVICE_URL
        value: "https://agriconnect-voice-ai.onrender.com"
    autoDeploy: true

  - type: web
    name: agriconnect-voice-ai
    env: python
    region: singapore
    plan: free
    rootDir: ai-service
    buildCommand: "wget https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip && unzip -o vosk-model-small-en-us-0.15.zip && mv vosk-model-small-en-us-0.15 model_en && rm vosk-model-small-en-us-0.15.zip && pip install -r requirements.txt"
    startCommand: "uvicorn voice_app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: agriconnect-cv-ai
    env: python
    region: singapore
    plan: free
    rootDir: ai-service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn cv_app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
